# Generated by Django 3.2.6 on 2021-12-27 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat_menyurat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratkeluar',
            name='tujuan_instansi',
            field=models.ForeignKey(help_text='Jika tujuan instansi tidak ada, silahkan ke menu instansi', on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.instansi'),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='asal_instansi',
            field=models.ForeignKey(help_text='Jika asal instansi tidak ada, silahkan ke menu instansi', on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.instansi'),
        ),
    ]
